version: '3'
services:

  # nestjs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nestjs
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"

  sonarqube:
    image: "sonarqube:latest"
    container_name: sonarqube
    ports:
      - "9000:9000"

    environment:
      - SONARQUBE_JDBC_URL=jdbc:h2:tcp://sonarqube-db/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    volumes:
      - ./data/sonarqube:/opt/sonarqube/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=redis
      - REDIS_PORT=6379
    ports:
      - "8081:8081"
